// data.js
// Exposes DATA globally for app.js
window.DATA = [
  {"country":"Afghanistan","capitals":["Kabul"]},
  {"country":"Albania","capitals":["Tirana"]},
  {"country":"Algeria","capitals":["Algiers"]},
  {"country":"Andorra","capitals":["Andorra la Vella"]},
  {"country":"Angola","capitals":["Luanda"]},
  {"country":"Antigua and Barbuda","capitals":["Saint John's"]},
  {"country":"Argentina","capitals":["Buenos Aires"]},
  {"country":"Armenia","capitals":["Yerevan"]},
  {"country":"Australia","capitals":["Canberra"]},
  {"country":"Austria","capitals":["Vienna"]},
  {"country":"Azerbaijan","capitals":["Baku"]},
  {"country":"Bahamas","capitals":["Nassau"]},
  {"country":"Bahrain","capitals":["Manama"]},
  {"country":"Bangladesh","capitals":["Dhaka"]},
  {"country":"Barbados","capitals":["Bridgetown"]},
  {"country":"Belarus","capitals":["Minsk"]},
  {"country":"Belgium","capitals":["Brussels"]},
  {"country":"Belize","capitals":["Belmopan"]},
  {"country":"Benin","capitals":["Porto-Novo"]},
  {"country":"Bhutan","capitals":["Thimphu"]},
  {"country":"Bolivia","capitals":["Sucre"]},
  {"country":"Bosnia and Herzegovina","capitals":["Sarajevo"]},
  {"country":"Botswana","capitals":["Gaborone"]},
  {"country":"Brazil","capitals":["Brasília"]},
  {"country":"Brunei","capitals":["Bandar Seri Begawan"]},
  {"country":"Bulgaria","capitals":["Sofia"]},
  {"country":"Burkina Faso","capitals":["Ouagadougou"]},
  {"country":"Burundi","capitals":["Gitega"]},
  {"country":"Cabo Verde","capitals":["Praia"]},
  {"country":"Cambodia","capitals":["Phnom Penh"]},
  {"country":"Cameroon","capitals":["Yaoundé"]},
  {"country":"Canada","capitals":["Ottawa"]},
  {"country":"Central African Republic","capitals":["Bangui"]},
  {"country":"Chad","capitals":["N'Djamena"]},
  {"country":"Chile","capitals":["Santiago"]},
  {"country":"China","capitals":["Beijing"]},
  {"country":"Colombia","capitals":["Bogotá"]},
  {"country":"Comoros","capitals":["Moroni"]},
  {"country":"Congo","capitals":["Brazzaville"]},
  {"country":"Costa Rica","capitals":["San José"]},
  {"country":"Côte d'Ivoire","capitals":["Yamoussoukro"]},
  {"country":"Croatia","capitals":["Zagreb"]},
  {"country":"Cuba","capitals":["Havana"]},
  {"country":"Cyprus","capitals":["Nicosia"]},
  {"country":"Czechia","capitals":["Prague"]},
  {"country":"Democratic Republic of the Congo","capitals":["Kinshasa"]},
  {"country":"Denmark","capitals":["Copenhagen"]},
  {"country":"Djibouti","capitals":["Djibouti"]},
  {"country":"Dominica","capitals":["Roseau"]},
  {"country":"Dominican Republic","capitals":["Santo Domingo"]},
  {"country":"Ecuador","capitals":["Quito"]},
  {"country":"Egypt","capitals":["Cairo"]},
  {"country":"El Salvador","capitals":["San Salvador"]},
  {"country":"Equatorial Guinea","capitals":["Malabo"]},
  {"country":"Eritrea","capitals":["Asmara"]},
  {"country":"Estonia","capitals":["Tallinn"]},
  {"country":"Eswatini","capitals":["Mbabane"]},
  {"country":"Ethiopia","capitals":["Addis Ababa"]},
  {"country":"Fiji","capitals":["Suva"]},
  {"country":"Finland","capitals":["Helsinki"]},
  {"country":"France","capitals":["Paris"]},
  {"country":"Gabon","capitals":["Libreville"]},
  {"country":"Gambia","capitals":["Banjul"]},
  {"country":"Georgia","capitals":["Tbilisi"]},
  {"country":"Germany","capitals":["Berlin"]},
  {"country":"Ghana","capitals":["Accra"]},
  {"country":"Greece","capitals":["Athens"]},
  {"country":"Grenada","capitals":["St. George's"]},
  {"country":"Guatemala","capitals":["Guatemala City"]},
  {"country":"Guinea","capitals":["Conakry"]},
  {"country":"Guinea-Bissau","capitals":["Bissau"]},
  {"country":"Guyana","capitals":["Georgetown"]},
  {"country":"Haiti","capitals":["Port-au-Prince"]},
  {"country":"Honduras","capitals":["Tegucigalpa"]},
  {"country":"Hungary","capitals":["Budapest"]},
  {"country":"Iceland","capitals":["Reykjavík"]},
  {"country":"India","capitals":["New Delhi"]},
  {"country":"Indonesia","capitals":["Jakarta"]},
  {"country":"Iran","capitals":["Tehran"]},
  {"country":"Iraq","capitals":["Baghdad"]},
  {"country":"Ireland","capitals":["Dublin"]},
  {"country":"Israel","capitals":["Jerusalem"]},
  {"country":"Italy","capitals":["Rome"]},
  {"country":"Jamaica","capitals":["Kingston"]},
  {"country":"Japan","capitals":["Tokyo"]},
  {"country":"Jordan","capitals":["Amman"]},
  {"country":"Kazakhstan","capitals":["Astana"]},
  {"country":"Kenya","capitals":["Nairobi"]},
  {"country":"Kiribati","capitals":["South Tarawa"]},
  {"country":"Kuwait","capitals":["Kuwait City"]},
  {"country":"Kyrgyzstan","capitals":["Bishkek"]},
  {"country":"Laos","capitals":["Vientiane"]},
  {"country":"Latvia","capitals":["Riga"]},
  {"country":"Lebanon","capitals":["Beirut"]},
  {"country":"Lesotho","capitals":["Maseru"]},
  {"country":"Liberia","capitals":["Monrovia"]},
  {"country":"Libya","capitals":["Tripoli"]},
  {"country":"Liechtenstein","capitals":["Vaduz"]},
  {"country":"Lithuania","capitals":["Vilnius"]},
  {"country":"Luxembourg","capitals":["Luxembourg"]},
  {"country":"Madagascar","capitals":["Antananarivo"]},
  {"country":"Malawi","capitals":["Lilongwe"]},
  {"country":"Malaysia","capitals":["Kuala Lumpur"]},
  {"country":"Maldives","capitals":["Malé"]},
  {"country":"Mali","capitals":["Bamako"]},
  {"country":"Malta","capitals":["Valletta"]},
  {"country":"Marshall Islands","capitals":["Majuro"]},
  {"country":"Mauritania","capitals":["Nouakchott"]},
  {"country":"Mauritius","capitals":["Port Louis"]},
  {"country":"Mexico","capitals":["Mexico City"]},
  {"country":"Micronesia","capitals":["Palikir"]},
  {"country":"Moldova","capitals":["Chișinău"]},
  {"country":"Monaco","capitals":["Monaco"]},
  {"country":"Mongolia","capitals":["Ulaanbaatar"]},
  {"country":"Montenegro","capitals":["Podgorica"]},
  {"country":"Morocco","capitals":["Rabat"]},
  {"country":"Mozambique","capitals":["Maputo"]},
  {"country":"Myanmar","capitals":["Naypyidaw"]},
  {"country":"Namibia","capitals":["Windhoek"]},
  {"country":"Nauru","capitals":["Yaren"]},
  {"country":"Nepal","capitals":["Kathmandu"]},
  {"country":"Netherlands","capitals":["Amsterdam"]},
  {"country":"New Zealand","capitals":["Wellington"]},
  {"country":"Nicaragua","capitals":["Managua"]},
  {"country":"Niger","capitals":["Niamey"]},
  {"country":"Nigeria","capitals":["Abuja"]},
  {"country":"North Korea","capitals":["Pyongyang"]},
  {"country":"North Macedonia","capitals":["Skopje"]},
  {"country":"Norway","capitals":["Oslo"]},
  {"country":"Oman","capitals":["Muscat"]},
  {"country":"Pakistan","capitals":["Islamabad"]},
  {"country":"Palau","capitals":["Ngerulmud"]},
  {"country":"Panama","capitals":["Panama City"]},
  {"country":"Papua New Guinea","capitals":["Port Moresby"]},
  {"country":"Paraguay","capitals":["Asunción"]},
  {"country":"Peru","capitals":["Lima"]},
  {"country":"Philippines","capitals":["Manila"]},
  {"country":"Poland","capitals":["Warsaw"]},
  {"country":"Portugal","capitals":["Lisbon"]},
  {"country":"Qatar","capitals":["Doha"]},
  {"country":"Romania","capitals":["Bucharest"]},
  {"country":"Russia","capitals":["Moscow"]},
  {"country":"Rwanda","capitals":["Kigali"]},
  {"country":"Saint Kitts and Nevis","capitals":["Basseterre"]},
  {"country":"Saint Lucia","capitals":["Castries"]},
  {"country":"Saint Vincent and the Grenadines","capitals":["Kingstown"]},
  {"country":"Samoa","capitals":["Apia"]},
  {"country":"San Marino","capitals":["San Marino"]},
  {"country":"Sao Tome and Principe","capitals":["São Tomé"]},
  {"country":"Saudi Arabia","capitals":["Riyadh"]},
  {"country":"Senegal","capitals":["Dakar"]},
  {"country":"Serbia","capitals":["Belgrade"]},
  {"country":"Seychelles","capitals":["Victoria"]},
  {"country":"Sierra Leone","capitals":["Freetown"]},
  {"country":"Singapore","capitals":["Singapore"]},
  {"country":"Slovakia","capitals":["Bratislava"]},
  {"country":"Slovenia","capitals":["Ljubljana"]},
  {"country":"Solomon Islands","capitals":["Honiara"]},
  {"country":"Somalia","capitals":["Mogadishu"]},
  {"country":"South Africa","capitals":["Pretoria"]},
  {"country":"South Sudan","capitals":["Juba"]},
  {"country":"Spain","capitals":["Madrid"]},
  {"country":"Sri Lanka","capitals":["Sri Jayawardenepura Kotte"]},
  {"country":"Sudan","capitals":["Khartoum"]},
  {"country":"Suriname","capitals":["Paramaribo"]},
  {"country":"Sweden","capitals":["Stockholm"]},
  {"country":"Switzerland","capitals":["Bern"]},
  {"country":"Syria","capitals":["Damascus"]},
  {"country":"Tajikistan","capitals":["Dushanbe"]},
  {"country":"Tanzania","capitals":["Dodoma"]},
  {"country":"Thailand","capitals":["Bangkok"]},
  {"country":"Timor-Leste","capitals":["Dili"]},
  {"country":"Togo","capitals":["Lomé"]},
  {"country":"Tonga","capitals":["Nukuʻalofa"]},
  {"country":"Trinidad and Tobago","capitals":["Port of Spain"]},
  {"country":"Tunisia","capitals":["Tunis"]},
  {"country":"Turkey","capitals":["Ankara"]},
  {"country":"Turkmenistan","capitals":["Ashgabat"]},
  {"country":"Tuvalu","capitals":["Funafuti"]},
  {"country":"Uganda","capitals":["Kampala"]},
  {"country":"Ukraine","capitals":["Kyiv"]},
  {"country":"United Arab Emirates","capitals":["Abu Dhabi"]},
  {"country":"United Kingdom","capitals":["London"]},
  {"country":"United States","capitals":["Washington, D.C."]},
  {"country":"Uruguay","capitals":["Montevideo"]},
  {"country":"Uzbekistan","capitals":["Tashkent"]},
  {"country":"Vanuatu","capitals":["Port Vila"]},
  {"country":"Vatican City","capitals":["Vatican City"]},
  {"country":"Venezuela","capitals":["Caracas"]},
  {"country":"Vietnam","capitals":["Hanoi"]},
  {"country":"Yemen","capitals":["Sana'a"]},
  {"country":"Zambia","capitals":["Lusaka"]},
  {"country":"Zimbabwe","capitals":["Harare"]}
];
