/**
 * Carmen suspects — roster + attribute taxonomy + witness-clue templates.
 *
 * Pure content. The game engine asks for SUSPECTS, attribute groupings, and the
 * vague/specific witness-clue templates that describe a suspect's hair / accessory
 * / hobby / vehicle. No DOM, no audio.
 */

export const SUSPECTS = [
  // Original suspects
  { name: 'Carmen Sandiego', hair: 'black', accessory: 'red trench coat', hobby: 'tango dancing', vehicle: 'red convertible',
    origin: 'Buenos Aires, Argentina', knownRegions: ['South America', 'Europe', 'Asia'],
    geoFact: 'Once corrected a customs officer that the Danube flows through 10 countries, not 9.',
    quirk: 'Cannot resist correcting geography mistakes', img: 'carmen/img/carmen-sandiego.png' },
  { name: 'Viktor Voss', hair: 'blond', accessory: 'monocle', hobby: 'chess', vehicle: 'submarine',
    origin: 'Vienna, Austria', knownRegions: ['Europe', 'North America'],
    geoFact: 'Won a chess tournament in every landlocked country in Europe.',
    quirk: 'Speaks in chess metaphors when cornered', img: 'carmen/img/Viktor Voss.png' },
  { name: 'Natasha Petrova', hair: 'red', accessory: 'fur hat', hobby: 'ice skating', vehicle: 'snowmobile',
    origin: 'Saint Petersburg, Russia', knownRegions: ['Europe', 'Asia'],
    geoFact: 'Claims to have skated across Lake Baikal, the deepest lake on Earth.',
    quirk: 'Leaves ice shavings at every crime scene', img: 'carmen/img/Natasha Petrova.png' },
  { name: 'El Zorro', hair: 'black', accessory: 'mask', hobby: 'fencing', vehicle: 'black stallion',
    origin: 'Seville, Spain', knownRegions: ['Europe', 'South America'],
    geoFact: 'Has visited every country along the Mediterranean coast — all 21 of them.',
    quirk: 'Carves a Z into museum walls before vanishing', img: 'carmen/img/El Zorro.png' },
  { name: 'The Shadow', hair: 'unknown', accessory: 'dark cloak', hobby: 'magic tricks', vehicle: 'motorcycle',
    origin: 'Unknown', knownRegions: ['Asia', 'Africa'],
    geoFact: 'Rumored to have crossed the Sahara — the world\'s largest hot desert — on foot.',
    quirk: 'Never photographed; witnesses disagree on all details', img: 'carmen/img/The Shadow.png' },
  { name: 'Lady Crimson', hair: 'auburn', accessory: 'ruby necklace', hobby: 'opera singing', vehicle: 'luxury yacht',
    origin: 'Monte Carlo, Monaco', knownRegions: ['Europe', 'Oceania'],
    geoFact: 'Her yacht has docked in ports of all 6 island nations of the Caribbean that border the Atlantic.',
    quirk: 'Only steals during a full moon', img: 'carmen/img/Lady Crimson.png' },
  { name: 'Phantom Fox', hair: 'silver', accessory: 'fox brooch', hobby: 'origami', vehicle: 'hang glider',
    origin: 'Kyoto, Japan', knownRegions: ['Asia', 'Oceania'],
    geoFact: 'Folds origami of each country she visits — Japan has 6,852 islands to fold.',
    quirk: 'Leaves an origami fox at the scene' },
  { name: 'Raven', hair: 'black', accessory: 'feathered hat', hobby: 'bird watching', vehicle: 'hot air balloon',
    origin: 'Quito, Ecuador', knownRegions: ['South America', 'Africa'],
    geoFact: 'Spotted a condor at 6,000m in the Andes — the longest continental mountain range.',
    quirk: 'Only operates at dawn or dusk', img: 'carmen/img/Raven.png' },
  { name: 'Scarlet Cipher', hair: 'red', accessory: 'coded tattoo', hobby: 'cryptography', vehicle: 'sports car',
    origin: 'Berlin, Germany', knownRegions: ['Europe', 'North America'],
    geoFact: 'Her coded messages reference the prime meridian — 0° longitude through Greenwich.',
    quirk: 'Encrypts ransom notes in geographic coordinates' },
  { name: 'Dr. Atlas', hair: 'gray', accessory: 'vintage compass', hobby: 'cartography', vehicle: 'seaplane',
    origin: 'Lisbon, Portugal', knownRegions: ['Europe', 'Africa', 'South America'],
    geoFact: 'Mapped every capital city within 500km of the equator.',
    quirk: 'Refuses to use GPS — only paper maps and compass', img: 'carmen/img/Dr. Atlas.png' },
  { name: 'The Cartographer', hair: 'brown', accessory: 'leather satchel', hobby: 'mountaineering', vehicle: 'jeep',
    origin: 'Kathmandu, Nepal', knownRegions: ['Asia', 'Africa'],
    geoFact: 'Has summited peaks on all seven continents — the Seven Summits challenge.',
    quirk: 'Takes a soil sample from every country visited', img: 'carmen/img/The Cartographer.png' },
  { name: 'Velvet Mask', hair: 'platinum', accessory: 'velvet gloves', hobby: 'ballroom dancing', vehicle: 'limousine',
    origin: 'Paris, France', knownRegions: ['Europe', 'North America'],
    geoFact: 'Once waltzed through the Hall of Mirrors at Versailles during a heist.',
    quirk: 'Always wears gloves — never leaves fingerprints', img: 'carmen/img/Velvet Mask.png' },

  // Added suspects (balanced overlap)
  { name: 'Raven Noir', hair: 'black', accessory: 'feathered hat', hobby: 'bird watching', vehicle: 'balloon',
    origin: 'Bogotá, Colombia', knownRegions: ['South America', 'North America'],
    geoFact: 'Colombia has more bird species than any other country — over 1,900.',
    quirk: 'Communicates through bird calls' },
  { name: 'Professor Paradox', hair: 'white', accessory: 'pocket watch', hobby: 'time theory', vehicle: 'experimental car',
    origin: 'Geneva, Switzerland', knownRegions: ['Europe', 'Asia'],
    geoFact: 'Studies time zones obsessively — China spans 5 geographic zones but uses only one.',
    quirk: 'Wears watches set to different time zones', img: 'carmen/img/Professor Paradox.png' },
  { name: 'Luna Nocturne', hair: 'silver', accessory: 'moon pendant', hobby: 'stargazing', vehicle: 'glider',
    origin: 'Reykjavik, Iceland', knownRegions: ['Europe', 'North America'],
    geoFact: 'Chases the northern lights — visible from Iceland due to its position near the Arctic Circle.',
    quirk: 'Only active during new moon phases', img: 'carmen/img/Luna Nocturne.png' },
  { name: 'Count Obsidian', hair: 'black', accessory: 'obsidian ring', hobby: 'antiquities', vehicle: 'helicopter',
    origin: 'Istanbul, Turkey', knownRegions: ['Europe', 'Asia', 'Africa'],
    geoFact: 'Istanbul straddles two continents — Europe and Asia — divided by the Bosphorus.',
    quirk: 'Collects volcanic glass from eruption sites' },
  { name: 'Ivy Virelli', hair: 'green', accessory: 'vine bracelet', hobby: 'botany', vehicle: 'bicycle',
    origin: 'Florence, Italy', knownRegions: ['Europe', 'South America'],
    geoFact: 'Studies the Amazon rainforest — it produces about 20% of the world\'s oxygen.',
    quirk: 'Grows rare plants in hidden greenhouses worldwide' },
  { name: 'Echo', hair: 'unknown', accessory: 'voice modulator', hobby: 'sound engineering', vehicle: 'drone',
    origin: 'Unknown', knownRegions: ['Asia', 'Oceania'],
    geoFact: 'Recorded echoes in the deepest canyon on Earth — the Yarlung Tsangpo Grand Canyon in Tibet.',
    quirk: 'Identity completely unknown; communicates only through distorted audio' },
  { name: 'The Locksmith', hair: 'brown', accessory: 'keychain', hobby: 'lockpicking', vehicle: 'van',
    origin: 'Prague, Czech Republic', knownRegions: ['Europe'],
    geoFact: 'Claims to have picked locks in every capital city of the EU\'s 27 member states.',
    quirk: 'Collects antique keys from every country' },
  { name: 'Captain Marlowe', hair: 'gray', accessory: 'captain hat', hobby: 'navigation', vehicle: 'cargo ship',
    origin: 'Liverpool, United Kingdom', knownRegions: ['Europe', 'Africa', 'Asia'],
    geoFact: 'Sailed through the Strait of Malacca — one of the busiest shipping lanes in the world.',
    quirk: 'Navigates by stars; refuses modern instruments', img: 'carmen/img/Captain Marlowe.png' },
  { name: 'Nova Vex', hair: 'red', accessory: 'visor', hobby: 'astronomy', vehicle: 'jet',
    origin: 'Houston, United States', knownRegions: ['North America', 'South America'],
    geoFact: 'Built an observatory in the Atacama Desert, Chile — driest place on Earth.',
    quirk: 'Names heists after constellations' },
  { name: 'Saffron Silk', hair: 'auburn', accessory: 'silk fan', hobby: 'tea ceremonies', vehicle: 'rickshaw',
    origin: 'Jaipur, India', knownRegions: ['Asia', 'Africa'],
    geoFact: 'Traveled the ancient Silk Road — 6,400 km from China to the Mediterranean.',
    quirk: 'Leaves a saffron thread at every scene' },

  { name: 'Silk Serpent', hair: 'black', accessory: 'gold earrings', hobby: 'dance', vehicle: 'motorbike',
    origin: 'Bangkok, Thailand', knownRegions: ['Asia', 'Oceania'],
    geoFact: 'Thailand is the only Southeast Asian country never colonized by a European power.',
    quirk: 'Vanishes into night markets without a trace', img: 'carmen/img/Silk Serpent.png' },
  { name: 'Crimson Dagger', hair: 'red', accessory: 'dagger', hobby: 'dueling', vehicle: 'motorcycle',
    origin: 'Marrakech, Morocco', knownRegions: ['Africa', 'Europe'],
    geoFact: 'Morocco is only 14 km from Spain across the Strait of Gibraltar.',
    quirk: 'Challenges rivals to duels before escaping' },
  { name: 'Golden Lynx', hair: 'blond', accessory: 'necklace', hobby: 'jewelry', vehicle: 'sports car',
    origin: 'Antwerp, Belgium', knownRegions: ['Europe', 'Africa'],
    geoFact: 'Antwerp handles 84% of the world\'s rough diamond trade.',
    quirk: 'Only steals gems — never gold' },
  { name: 'Ivory Whisper', hair: 'white', accessory: 'gloves', hobby: 'piano', vehicle: 'car',
    origin: 'Salzburg, Austria', knownRegions: ['Europe'],
    geoFact: 'Salzburg sits on the border with Germany — the Salzach River divides the two countries.',
    quirk: 'Plays a short piece on any piano found at the scene' },
  { name: 'Neon Specter', hair: 'green', accessory: 'visor', hobby: 'hacking', vehicle: 'motorbike',
    origin: 'Seoul, South Korea', knownRegions: ['Asia', 'North America'],
    geoFact: 'South Korea has the fastest average internet speed in the world.',
    quirk: 'Hacks digital billboards to taunt investigators' },
  { name: 'Scarlet Swan', hair: 'red', accessory: 'necklace', hobby: 'ballet', vehicle: 'car',
    origin: 'Moscow, Russia', knownRegions: ['Europe', 'Asia'],
    geoFact: 'Performed at the Bolshoi Theatre — Moscow sits on the Moskva River at 55°N latitude.',
    quirk: 'Leaves ballet slippers as a calling card' },

  { name: 'Midnight Owl', hair: 'black', accessory: 'glasses', hobby: 'reading', vehicle: 'bicycle',
    origin: 'Oxford, United Kingdom', knownRegions: ['Europe'],
    geoFact: 'The Thames flows through Oxford before reaching London — 346 km total length.',
    quirk: 'Steals only first editions; returns photocopies' },
  { name: 'Dusty Nomad', hair: 'brown', accessory: 'hat', hobby: 'traveling', vehicle: 'jeep',
    origin: 'Ulaanbaatar, Mongolia', knownRegions: ['Asia', 'Africa'],
    geoFact: 'Mongolia is the most sparsely populated country — about 2 people per km².',
    quirk: 'Never stays in one country for more than 48 hours', img: 'carmen/img/Dusty Nomad.png' },
  { name: 'Silver Comet', hair: 'silver', accessory: 'watch', hobby: 'running', vehicle: 'jet',
    origin: 'Nairobi, Kenya', knownRegions: ['Africa', 'Europe'],
    geoFact: 'Kenya\'s Great Rift Valley stretches 6,000 km from Lebanon to Mozambique.',
    quirk: 'Outruns any pursuer on foot' },
  { name: 'Velvet Raven', hair: 'black', accessory: 'cloak', hobby: 'poetry', vehicle: 'boat',
    origin: 'Dublin, Ireland', knownRegions: ['Europe', 'North America'],
    geoFact: 'Ireland is called the Emerald Isle — it rains on average 225 days per year.',
    quirk: 'Leaves handwritten poems at crime scenes' },
  { name: 'Amber Fox', hair: 'auburn', accessory: 'brooch', hobby: 'collecting', vehicle: 'car',
    origin: 'Gdańsk, Poland', knownRegions: ['Europe'],
    geoFact: 'The Baltic coast near Gdańsk has the world\'s largest amber deposits — 40 million years old.',
    quirk: 'Collects amber from every Baltic country' },

  { name: 'Storm Herald', hair: 'gray', accessory: 'coat', hobby: 'meteorology', vehicle: 'plane',
    origin: 'Reykjavik, Iceland', knownRegions: ['Europe', 'North America'],
    geoFact: 'Iceland sits on the Mid-Atlantic Ridge — where the Eurasian and North American plates diverge.',
    quirk: 'Strikes only during storms for cover' },
  { name: 'Crimson Mirage', hair: 'red', accessory: 'scarf', hobby: 'illusion', vehicle: 'train',
    origin: 'Cairo, Egypt', knownRegions: ['Africa', 'Asia'],
    geoFact: 'The Nile is the longest river in Africa at 6,650 km — passing through 11 countries.',
    quirk: 'Creates diversions using mirrors and light' },
  { name: 'Onyx Panther', hair: 'black', accessory: 'mask', hobby: 'stealth', vehicle: 'motorcycle',
    origin: 'Lagos, Nigeria', knownRegions: ['Africa', 'Europe'],
    geoFact: 'Nigeria is Africa\'s most populous country with over 220 million people.',
    quirk: 'Has never set off a single alarm' },
  { name: 'Golden Seraph', hair: 'blond', accessory: 'pendant', hobby: 'history', vehicle: 'ship',
    origin: 'Athens, Greece', knownRegions: ['Europe', 'Asia'],
    geoFact: 'Greece has more archaeological museums than any other country in the world.',
    quirk: 'Only targets artifacts from ancient civilizations', img: 'carmen/img/Golden Seraph.png' },
  { name: 'Ivory Phantom', hair: 'white', accessory: 'cloak', hobby: 'acting', vehicle: 'car',
    origin: 'Venice, Italy', knownRegions: ['Europe', 'South America'],
    geoFact: 'Venice is built on 118 small islands connected by over 400 bridges.',
    quirk: 'Masters disguises — changes identity at every border' },

  { name: 'Emerald Kite', hair: 'green', accessory: 'ring', hobby: 'kite flying', vehicle: 'glider',
    origin: 'Lahore, Pakistan', knownRegions: ['Asia'],
    geoFact: 'Pakistan contains K2, the second-highest mountain on Earth at 8,611m.',
    quirk: 'Uses kites to scout locations from above' },
  { name: 'Shadow Lynx', hair: 'black', accessory: 'gloves', hobby: 'tracking', vehicle: 'jeep',
    origin: 'Windhoek, Namibia', knownRegions: ['Africa'],
    geoFact: 'Namibia\'s Skeleton Coast is one of the world\'s most treacherous shorelines.',
    quirk: 'Can track any person across any terrain' },
  { name: 'Copper Sparrow', hair: 'auburn', accessory: 'hat', hobby: 'writing', vehicle: 'bicycle',
    origin: 'Havana, Cuba', knownRegions: ['North America', 'South America'],
    geoFact: 'Cuba is the largest island in the Caribbean — 1,250 km from tip to tip.',
    quirk: 'Publishes crime memoirs under a pen name' },
  { name: 'Ghost Mariner', hair: 'gray', accessory: 'compass', hobby: 'sailing', vehicle: 'ship',
    origin: 'Bergen, Norway', knownRegions: ['Europe', 'North America'],
    geoFact: 'Norway\'s coastline is over 25,000 km long — or 100,000 km including fjords.',
    quirk: 'Ship appears and vanishes like a phantom in fog' },
  { name: 'Velvet Cipher', hair: 'black', accessory: 'tattoo', hobby: 'cryptography', vehicle: 'car',
    origin: 'Tallinn, Estonia', knownRegions: ['Europe', 'Asia'],
    geoFact: 'Estonia is one of the most digitally advanced nations — 99% of government services are online.',
    quirk: 'Leaves encrypted clues that take weeks to decode' },
];

export const SUSPECT_ATTRIBUTES = ['hair', 'accessory', 'hobby', 'vehicle'];

const ATTRIBUTE_GROUPS = {
  hair: {
    dark:    ['black', 'brown'],
    light:   ['blond', 'auburn', 'platinum'],
    unusual: ['green', 'silver', 'white', 'gray', 'unknown'],
    red:     ['red'],
  },
  accessory: {
    headwear:  ['fur hat', 'feathered hat', 'captain hat', 'hat'],
    eyewear:   ['monocle', 'visor', 'glasses'],
    jewelry:   ['ruby necklace', 'moon pendant', 'obsidian ring', 'necklace', 'gold earrings', 'pendant', 'ring', 'vine bracelet', 'brooch', 'fox brooch'],
    outerwear: ['red trench coat', 'dark cloak', 'velvet gloves', 'gloves', 'cloak', 'coat', 'scarf'],
    gadget:    ['coded tattoo', 'vintage compass', 'leather satchel', 'pocket watch', 'voice modulator', 'keychain', 'watch', 'compass', 'tattoo'],
    other:     ['mask', 'dagger', 'silk fan'],
  },
  hobby: {
    physical:  ['tango dancing', 'ice skating', 'fencing', 'ballroom dancing', 'dance', 'dueling', 'ballet', 'running', 'stealth', 'tracking'],
    cerebral:  ['chess', 'cryptography', 'time theory', 'hacking', 'lockpicking', 'sound engineering', 'navigation'],
    artistic:  ['opera singing', 'origami', 'poetry', 'piano', 'acting', 'writing', 'illusion', 'magic tricks'],
    outdoors:  ['bird watching', 'cartography', 'mountaineering', 'botany', 'stargazing', 'astronomy', 'kite flying', 'sailing', 'meteorology', 'traveling'],
    collector: ['antiquities', 'jewelry', 'tea ceremonies', 'collecting', 'reading', 'history'],
  },
  vehicle: {
    air:  ['hang glider', 'hot air balloon', 'seaplane', 'balloon', 'glider', 'helicopter', 'drone', 'jet', 'plane'],
    land: ['red convertible', 'black stallion', 'motorcycle', 'jeep', 'limousine', 'experimental car', 'van', 'motorbike', 'car', 'bicycle', 'rickshaw', 'sports car', 'train'],
    sea:  ['submarine', 'luxury yacht', 'cargo ship', 'boat', 'ship', 'snowmobile'],
  },
};

export function getAttributeGroup(attr, value) {
  const groups = ATTRIBUTE_GROUPS[attr];
  if (!groups) return null;
  for (const [groupName, members] of Object.entries(groups)) {
    if (members.includes(value)) return groupName;
  }
  return null;
}

export const SUSPECT_CLUE_TEMPLATES_VAGUE = {
  hair: (group) => ({
    dark: 'A witness noticed the suspect had dark hair.',
    light: 'A witness described the suspect as having light-colored hair.',
    unusual: 'A witness said the suspect had unusual hair — not a natural color.',
    red: 'A witness recalls the suspect had reddish hair.',
  })[group] || `A witness said the suspect had ${group} hair.`,

  accessory: (group) => ({
    headwear: 'The suspect was seen wearing some kind of distinctive hat.',
    eyewear: 'The suspect was wearing something over their eyes.',
    jewelry: 'A bystander noticed the suspect was wearing jewelry.',
    outerwear: 'The suspect was wrapped in notable outerwear.',
    gadget: 'The suspect was carrying a notable accessory or gadget.',
    other: 'The suspect had something unusual on them.',
  })[group] || `The suspect had some kind of ${group}.`,

  hobby: (group) => ({
    physical: 'An informant says the thief is into physical activities or performance.',
    cerebral: 'The thief is reportedly a thinker — into puzzles or technical skills.',
    artistic: 'Sources say the thief has artistic or creative interests.',
    outdoors: 'The thief apparently enjoys outdoor or nature-related activities.',
    collector: 'Word is the thief is a collector or scholar of some kind.',
  })[group] || `The thief reportedly enjoys ${group} activities.`,

  vehicle: (group) => ({
    air: 'The getaway involved something that flies.',
    land: 'The thief escaped by land vehicle.',
    sea: 'The thief was last seen heading toward the water.',
  })[group] || `The getaway was by ${group}.`,
};

export const SUSPECT_CLUE_TEMPLATES_SPECIFIC = {
  hair:      (val) => `A witness positively identified the suspect as having ${val} hair.`,
  accessory: (val) => `The suspect was confirmed to be wearing a ${val}.`,
  hobby:     (val) => `A reliable source confirms the thief is known for ${val}.`,
  vehicle:   (val) => `The getaway vehicle has been identified as a ${val}.`,
};
